# Generated by Django 3.1.7 on 2021-04-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
