# Generated by Django 3.1.7 on 2021-04-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp2', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gender',
        ),
    ]
