# Generated by Django 3.1.7 on 2021-04-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp2', '0003_auto_20210425_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Train',
            new_name='Locations',
        ),
    ]
