# Generated by Django 3.1.7 on 2021-04-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp2', '0004_auto_20210429_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('mtd', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('cancel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('nos', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('cls', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pnr', models.CharField(max_length=50)),
                ('src', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=50)),
                ('ostation', models.CharField(max_length=50)),
                ('dstation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('atime', models.CharField(max_length=50)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp2.route')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('tno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp2.route')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='routestation',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp2.station'),
        ),
        migrations.AddField(
            model_name='routestation',
            name='tno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp2.trains'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp2.trains'),
        ),
    ]
