# Generated by Django 3.1.7 on 2021-04-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp2', '0004_auto_20210425_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_No', models.IntegerField()),
                ('Train_Source', models.CharField(max_length=255)),
                ('Train_Destination', models.CharField(max_length=255)),
                ('Train_Name', models.CharField(max_length=255)),
                ('Train_Type', models.CharField(max_length=255)),
            ],
        ),
    ]
