# Generated by Django 3.1.7 on 2021-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='hotels',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='nbeds',
            field=models.IntegerField(null=True),
        ),
    ]
