# Generated by Django 3.0.7 on 2021-05-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_auto_20210503_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=20),
        ),
    ]
