# Generated by Django 3.1.7 on 2021-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shotel', '0002_auto_20210501_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='rooms',
            field=models.CharField(choices=[('AC', 'AC Rooms'), ('N-AC', 'Non-AC Rooms'), ('Deluxe', 'Deluxe Rooms'), ('S-Deluxe', 'Super Deluxe Rooms')], max_length=100, null=True),
        ),
    ]
