# Generated by Django 3.1.7 on 2021-05-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shotel', '0003_hotels_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='profile',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
