# Generated by Django 3.1.7 on 2021-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shotel', '0004_hotels_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('New Delhi', 'New Delhi'), ('Kolkata', 'Kolkata'), ('Chennai', 'Chennai'), ('Bengaluru', 'Bengaluru')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='profile',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
    ]
