# Generated by Django 3.1.7 on 2021-05-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shotel', '0005_auto_20210501_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='descp1',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='descp2',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='descp3',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hcontact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='hemail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='mdescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='title1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='title2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='title3',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
